// Generated by gencpp from file learning_communication/bianshi.msg
// DO NOT EDIT!


#ifndef LEARNING_COMMUNICATION_MESSAGE_BIANSHI_H
#define LEARNING_COMMUNICATION_MESSAGE_BIANSHI_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learning_communication
{
template <class ContainerAllocator>
struct bianshi_
{
  typedef bianshi_<ContainerAllocator> Type;

  bianshi_()
    : g(0.0)
    , fx(0.0)
    , fy(0.0)
    , fz(0.0)
    , tx(0.0)
    , ty(0.0)
    , tz(0.0)
    , x(0.0)
    , y(0.0)
    , px(0.0)
    , py(0.0)
    , pz(0.0)  {
    }
  bianshi_(const ContainerAllocator& _alloc)
    : g(0.0)
    , fx(0.0)
    , fy(0.0)
    , fz(0.0)
    , tx(0.0)
    , ty(0.0)
    , tz(0.0)
    , x(0.0)
    , y(0.0)
    , px(0.0)
    , py(0.0)
    , pz(0.0)  {
  (void)_alloc;
    }



   typedef double _g_type;
  _g_type g;

   typedef double _fx_type;
  _fx_type fx;

   typedef double _fy_type;
  _fy_type fy;

   typedef double _fz_type;
  _fz_type fz;

   typedef double _tx_type;
  _tx_type tx;

   typedef double _ty_type;
  _ty_type ty;

   typedef double _tz_type;
  _tz_type tz;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _px_type;
  _px_type px;

   typedef double _py_type;
  _py_type py;

   typedef double _pz_type;
  _pz_type pz;





  typedef boost::shared_ptr< ::learning_communication::bianshi_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learning_communication::bianshi_<ContainerAllocator> const> ConstPtr;

}; // struct bianshi_

typedef ::learning_communication::bianshi_<std::allocator<void> > bianshi;

typedef boost::shared_ptr< ::learning_communication::bianshi > bianshiPtr;
typedef boost::shared_ptr< ::learning_communication::bianshi const> bianshiConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learning_communication::bianshi_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learning_communication::bianshi_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace learning_communication

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'learning_communication': ['/home/xsm/control/src/learning_communication/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::learning_communication::bianshi_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_communication::bianshi_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_communication::bianshi_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_communication::bianshi_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_communication::bianshi_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_communication::bianshi_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learning_communication::bianshi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ef0f20add1753e4de26579161d3d529";
  }

  static const char* value(const ::learning_communication::bianshi_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ef0f20add1753e4ULL;
  static const uint64_t static_value2 = 0xde26579161d3d529ULL;
};

template<class ContainerAllocator>
struct DataType< ::learning_communication::bianshi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learning_communication/bianshi";
  }

  static const char* value(const ::learning_communication::bianshi_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learning_communication::bianshi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 g\n\
float64 fx\n\
float64 fy\n\
float64 fz\n\
float64 tx\n\
float64 ty\n\
float64 tz\n\
float64 x\n\
float64 y\n\
float64 px\n\
float64 py\n\
float64 pz\n\
\n\
";
  }

  static const char* value(const ::learning_communication::bianshi_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learning_communication::bianshi_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.g);
      stream.next(m.fx);
      stream.next(m.fy);
      stream.next(m.fz);
      stream.next(m.tx);
      stream.next(m.ty);
      stream.next(m.tz);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.px);
      stream.next(m.py);
      stream.next(m.pz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bianshi_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learning_communication::bianshi_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learning_communication::bianshi_<ContainerAllocator>& v)
  {
    s << indent << "g: ";
    Printer<double>::stream(s, indent + "  ", v.g);
    s << indent << "fx: ";
    Printer<double>::stream(s, indent + "  ", v.fx);
    s << indent << "fy: ";
    Printer<double>::stream(s, indent + "  ", v.fy);
    s << indent << "fz: ";
    Printer<double>::stream(s, indent + "  ", v.fz);
    s << indent << "tx: ";
    Printer<double>::stream(s, indent + "  ", v.tx);
    s << indent << "ty: ";
    Printer<double>::stream(s, indent + "  ", v.ty);
    s << indent << "tz: ";
    Printer<double>::stream(s, indent + "  ", v.tz);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "px: ";
    Printer<double>::stream(s, indent + "  ", v.px);
    s << indent << "py: ";
    Printer<double>::stream(s, indent + "  ", v.py);
    s << indent << "pz: ";
    Printer<double>::stream(s, indent + "  ", v.pz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARNING_COMMUNICATION_MESSAGE_BIANSHI_H
